### ISSUE TITLE
检查更新报错了

### ISSUE THREAD

**Issue by qsm-mz-hn** [hanasa2023/nonebot-plugin-updater#15]
12-30 23:52:06 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=38) failed.
Traceback (most recent call last):
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpx\_transports\default.py", line 72, in map_httpcore_exceptions
    yield
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpx\_transports\default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpcore\_async\connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpcore\_async\connection.py", line 99, in handle_async_request
    raise exc
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpcore\_async\connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpcore\_async\connection.py", line 154, in _connect
    stream = await stream.start_tls(**kwargs)
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpcore\_backends\anyio.py", line 69, in start_tls
    with map_exceptions(exc_map):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "C:\Nonebot\Bot\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Nonebot\Bot\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Nonebot\Bot\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "C:\Nonebot\Bot\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1899, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Nonebot\Bot\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Nonebot\Bot\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Nonebot\Bot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Nonebot\Bot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Nonebot\Bot\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Nonebot\Bot\.venv\lib\site-packages\nonebot_plugin_updater\commands.py", line 94, in _
    plugin_update_list: list[PluginInfo] = await get_plugin_update_list()
  File "C:\Nonebot\Bot\.venv\lib\site-packages\nonebot_plugin_updater\utils\common.py", line 86, in get_plugin_update_list
    store_plugins: list[NBPluginMetadata] = await get_store_plugins()
  File "C:\Nonebot\Bot\.venv\lib\site-packages\nonebot_plugin_updater\utils\common.py", line 20, in get_store_plugins
    response: httpx.Response = await ctx.get(
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpx\_client.py", line 1814, in get
    return await self.request(
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpx\_client.py", line 1585, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpx\_client.py", line 1674, in send
    response = await self._send_handling_auth(
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpx\_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpx\_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpx\_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpx\_transports\default.py", line 376, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Nonebot\Bot\.venv\lib\site-packages\httpx\_transports\default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError

**Comment by hanasa2023** [comment]
根据我这边的测试结果，应该是默认使用的github代理炸了。您可以根据文档配置稳定的github代理，以解决此问题。例如：`https://ghproxy.cn`。
