### ISSUE TITLE
[Bug?]希望可以增加排除部分插件的功能

### ISSUE THREAD

**Issue by enKl03B** [hanasa2023/nonebot-plugin-updater#4]
我使用的bot中，有一个插件并未上传(自用)
但插件检查更新时，还是会检查该插件，最终报错退出

```
Running AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=40) failed.
Traceback (most recent call last):
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 425, in from_name
    return next(iter(cls._prefer_valid(cls.discover(name=name))))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/commands.py", line 105, in _
    plugin_update_list = await get_plugin_update_list()
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/utils/common.py", line 59, in get_plugin_update_list
    current_version = importlib_metadata.version(module)
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 1027, in version
    return distribution(distribution_name).version
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 1000, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/lxm/桌面/Bot/nb01/nb01/.venv/lib/python3.10/site-packages/importlib_metadata/__init__.py", line 427, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for nonebot_plugin_welcome

```
（nonebot_plugin_welcome就是一个并没有上传的自用插件）

不过获取插件列表功能中排除了这个插件（只获取到了有上传的插件）
是否可以通过更新获取的列表中的插件以避免上述情况发生？

（好像有点apt update的样子

**Comment by hanasa2023** [comment]
可以尝试0.1.7是否修复，请注意此版本的指令鉴权

**Comment by hanasa2023** [comment]
可以试试>=0.1.8的版本。从0.1.8开始，启动不自动加载plugin-htmlrender，填写info_send_mode为text后，则不加载htmlrender

**Comment by enKl03B** [comment]
> 可以尝试0.1.7是否修复，请注意此版本的指令鉴权

已解决
