### ISSUE TITLE
[bug]:对于非GitHub仓库的插件可能出现错误

### ISSUE THREAD

**Issue by shi-yingyingjiang** [hanasa2023/nonebot-plugin-updater#6]
```python
10-15 11:43:29 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=38) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\importlib_metadata\__init__.py", line 412, in from_name
    return next(iter(cls.discover(name=name)))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\bot.py", line 67, in <module>
    nonebot.run()
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot_plugin_updater\commands.py", line 94, in _
    plugin_update_list: list[PluginInfo] = await get_plugin_update_list()
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot_plugin_updater\utils\common.py", line 88, in get_plugin_update_list
    current_version: str = importlib_metadata.version(module)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\importlib_metadata\__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\importlib_metadata\__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\importlib_metadata\__init__.py", line 414, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for nonebot_plugin_saa
```

**Comment by hanasa2023** [comment]
可以尝试^0.1.9，是否解决该问题

**Comment by shi-yingyingjiang** [comment]
哦又发了新包

**Comment by hanasa2023** [comment]
🤔

**Comment by hanasa2023** [comment]
如果已解决的话能不能麻烦关一下issue，问题不知道有没有解决我也很困扰
